package forge

import (
	"fmt"
)

func Coverage() error {
	fmt.Println("Forge coverage executed Successfully")
	return nil
}
